# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply two matrices using Eigen library
#'
#' This function multiplies two matrices using the Eigen library, which provides
#' fast linear algebra operations.
#'
#' @param A a matrix
#' @param B a matrix
#' @return the product of A and B
#' @useDynLib SPACO
#' @export
eigenMapMatMult <- function(A, B) {
    .Call('_SPACO_eigenMapMatMult', PACKAGE = 'SPACO', A, B)
}

